"""Pre-render every spoken Japanese line to an MP3 with a neural voice.

Why not just use the browser's speechSynthesis at runtime:
  - iOS Safari needs a user gesture and often has no Japanese voice at all,
    and the Challenge phase is audio-only, so a missing voice makes it
    unplayable rather than merely worse.
  - Voice quality varies wildly per device; pronunciation is the one thing a
    language app cannot afford to get wrong.

Generation needs network (it calls Microsoft's endpoint). Playback afterwards
is fully offline: the files are pre-cached by the service worker.

Files are named by a hash of the text, so re-running only regenerates lines
that actually changed. Delete assets/audio to force a full rebuild.

Usage:  python generate-audio.py
        python generate-audio.py --only audio-pending.txt

--only renders just the lines listed in the file (one per line), adds them to
the existing audio-index.js, and prunes nothing - for recording a few edited
lines without re-rendering or deleting anything else.
"""
import asyncio
import hashlib
import json
import os
import subprocess
import sys

import edge_tts

VOICE = 'ja-JP-NanamiNeural'
OUT_DIR = os.path.join('assets', 'audio')
INDEX_JS = 'audio-index.js'

# Slightly slower than default: these are study sentences, not narration.
RATE = '-8%'

def collect_groups():
    """Spoken lines grouped by when a player can first reach them.

    Grouped rather than flat because sw.js pre-caches only the "shell" group at
    install. See collect-spoken-lines.js for why.
    """
    result = subprocess.run(
        ['node', 'collect-spoken-lines.js', '--groups'],
        capture_output=True, text=True, encoding='utf-8'
    )
    if result.returncode != 0:
        sys.exit('failed to read stage data:\n' + result.stderr)
    return json.loads(result.stdout)


def key_for(text):
    return hashlib.sha1(text.encode('utf-8')).hexdigest()[:12]


# Every existing clip is MPEG-2 Layer III, 48 kbps, 24 kHz, mono. Only missing
# lines are rendered, so clips accumulate across runs and edge_tts versions;
# one that came out differently would sound different mid-lesson.
EXPECTED_HEADER = {'version': 2, 'layer': 1, 'bitrate': 6, 'rate': 1, 'mono': True}


def mp3_header(path):
    data = open(path, 'rb').read()
    at = 0
    if data[:3] == b'ID3':
        at = 10 + ((data[6] << 21) | (data[7] << 14) | (data[8] << 7) | data[9])
    while at < len(data) - 4 and not (data[at] == 0xFF and (data[at + 1] & 0xE0) == 0xE0):
        at += 1
    return {
        'version': (data[at + 1] >> 3) & 3,
        'layer': (data[at + 1] >> 1) & 3,
        'bitrate': (data[at + 2] >> 4) & 15,
        'rate': (data[at + 2] >> 2) & 3,
        'mono': ((data[at + 3] >> 6) & 3) == 3,
    }


async def render(text, path):
    speech = edge_tts.Communicate(text, VOICE, rate=RATE)
    await speech.save(path)
    found = mp3_header(path)
    if found != EXPECTED_HEADER:
        os.remove(path)
        sys.exit('rendered %s in a different format from every other clip:\n'
                 '  got      %s\n  expected %s\n'
                 'Check the installed edge_tts version before re-running.'
                 % (os.path.basename(path), found, EXPECTED_HEADER))


def read_index():
    """The two maps already in audio-index.js, so --only can add to them."""
    text = open(INDEX_JS, encoding='utf-8').read()
    audio = text.split('self.LanternAlleyAudio = ', 1)[1].split(';\n', 1)[0]
    grouped = text.split('self.LanternAlleyAudioGroups = ', 1)[1].rsplit(';', 1)[0]
    return json.loads(audio), json.loads(grouped)


def write_index(index, group_paths):
    # A .js file rather than .json so it works over file:// too, where fetch()
    # of a local JSON file is blocked as a cross-origin request.
    #
    # Assigned to `self`, not `window`: in a page self === window, and in the
    # service worker self is the worker global. That lets sw.js importScripts()
    # this same file to build its pre-cache list, so the audio paths have one
    # source of truth instead of being copied into two places.
    body = (
        '/* Generated by generate-audio.py - do not edit.\n'
        '   Maps each spoken line to its pre-rendered %s clip. */\n'
        'self.LanternAlleyAudio = %s;\n'
        '\n'
        '/* The same clips, grouped by when a player can first reach them.\n'
        '   sw.js pre-caches only "shell" at install and fetches an episode\n'
        '   stage when it unlocks - the full set is 26.6 MB, of which 24.4 MB\n'
        '   is behind progression gates. Groups are disjoint and together hold\n'
        '   every path in the map above. */\n'
        'self.LanternAlleyAudioGroups = %s;\n'
    ) % (
        VOICE,
        json.dumps(index, ensure_ascii=False, indent=2, sort_keys=True),
        json.dumps(group_paths, ensure_ascii=False, indent=2, sort_keys=True),
    )
    open(INDEX_JS, 'w', encoding='utf-8', newline='').write(body)


async def render_only(list_path):
    wanted = [l.strip() for l in open(list_path, encoding='utf-8') if l.strip()]
    group_of = {text: name for name, texts in collect_groups().items() for text in texts}
    unknown = [text for text in wanted if text not in group_of]
    if unknown:
        # A line the game never speaks would be cached for nothing, and one
        # with a typo would be recorded under a key nothing looks up.
        sys.exit('not a line the game speaks:\n  ' + '\n  '.join(unknown))
    index, group_paths = read_index()
    os.makedirs(OUT_DIR, exist_ok=True)
    for text in wanted:
        name = key_for(text) + '.mp3'
        path = os.path.join(OUT_DIR, name)
        rel = OUT_DIR.replace(os.sep, '/') + '/' + name
        if not (os.path.exists(path) and os.path.getsize(path) > 0):
            await render(text, path)
            print('  rendered  %s  %s' % (name, text[:34]))
        index[text] = rel
        paths = group_paths.setdefault(group_of[text], [])
        if rel not in paths:
            paths.append(rel)
    write_index(index, group_paths)
    print('\n%d lines recorded, nothing pruned; wrote %s' % (len(wanted), INDEX_JS))


async def main():
    if len(sys.argv) == 3 and sys.argv[1] == '--only':
        await render_only(sys.argv[2])
        return
    groups = collect_groups()
    lines = [text for group in groups.values() for text in group]
    os.makedirs(OUT_DIR, exist_ok=True)

    index = {}
    made = skipped = 0

    for text in lines:
        name = key_for(text) + '.mp3'
        path = os.path.join(OUT_DIR, name)
        index[text] = OUT_DIR.replace(os.sep, '/') + '/' + name

        if os.path.exists(path) and os.path.getsize(path) > 0:
            skipped += 1
            continue
        await render(text, path)
        made += 1
        print('  rendered  %s  %s' % (name, text[:34]))

    # Paths rather than lines: the worker wants a cache list, and repeating the
    # Japanese would double the size of this file for nothing.
    group_paths = {
        name: [index[text] for text in texts] for name, texts in groups.items()
    }
    write_index(index, group_paths)

    # Drop clips for lines that no longer exist, so edited sentences do not
    # leave their old audio behind to be shipped and cached forever.
    wanted = {key_for(text) + '.mp3' for text in lines}
    pruned = 0
    for name in os.listdir(OUT_DIR):
        if name.endswith('.mp3') and name not in wanted:
            os.remove(os.path.join(OUT_DIR, name))
            pruned += 1
            print('  pruned    %s' % name)

    total = sum(os.path.getsize(os.path.join(OUT_DIR, f)) for f in os.listdir(OUT_DIR))
    print('\n%d lines: %d rendered, %d unchanged, %d pruned' % (len(lines), made, skipped, pruned))
    print('%s  %.0f KB total' % (OUT_DIR, total / 1024))
    print('wrote %s' % INDEX_JS)


asyncio.run(main())
