"""Pre-render every spoken Japanese line to an MP3 with a neural voice.

Why not just use the browser's speechSynthesis at runtime:
  - iOS Safari needs a user gesture and often has no Japanese voice at all,
    and the Challenge phase is audio-only, so a missing voice makes it
    unplayable rather than merely worse.
  - Voice quality varies wildly per device; pronunciation is the one thing a
    language app cannot afford to get wrong.

Generation needs network (it calls Microsoft's endpoint). Playback afterwards
is fully offline: the files are pre-cached by the service worker.

Files are named by a hash of the text, so re-running only regenerates lines
that actually changed. Delete assets/audio to force a full rebuild.

Usage:  python generate-audio.py
"""
import asyncio
import hashlib
import json
import os
import subprocess
import sys

import edge_tts

VOICE = 'ja-JP-NanamiNeural'
OUT_DIR = os.path.join('assets', 'audio')
INDEX_JS = 'audio-index.js'

# Slightly slower than default: these are study sentences, not narration.
RATE = '-8%'

EXTRACT = r'''
const fs = require('fs'), vm = require('vm');
const ctx = {};
vm.createContext(ctx);
vm.runInContext(fs.readFileSync('entrance-stage-logic.js', 'utf8'), ctx);
vm.runInContext(fs.readFileSync('moonview-inn-interactions.js', 'utf8'), ctx);
vm.runInContext(fs.readFileSync('n2-home-inn-stage.js', 'utf8'), ctx);
const E = ctx.LanternAlleyLogic;
const S = ctx.N2HomeInnStage;
const out = new Set();
const add = (t) => { if (typeof t === 'string' && /[ぁ-んァ-ン一-龯]/.test(t)) out.add(t.trim()); };

let tutorial = E.createTutorial();
add(E.getTutorialStep(tutorial).jp);
tutorial = E.advanceTutorial(tutorial);
add(E.getTutorialStep(tutorial).jp);
tutorial = E.advanceTutorial(tutorial);
add(E.getTutorialStep(tutorial).jp);
tutorial = E.completeTutorial(tutorial);
add(E.getTutorialStep(tutorial).jp);

[...S.encounters, ...S.practice, ...S.challenge].forEach((item) => {
  add(item.jp);
  add(item.narration);
});
if (S.intro) { add(S.intro.jp); add(S.intro.context); add(S.intro.accept); }
[...S.encounters, ...S.practice, ...S.challenge].forEach((item) => {
  (item.interaction && item.interaction.replies || []).forEach((r) => add(r.label));
});
console.log(JSON.stringify([...out]));
'''


def collect_lines():
    result = subprocess.run(
        ['node', '-e', EXTRACT], capture_output=True, text=True, encoding='utf-8'
    )
    if result.returncode != 0:
        sys.exit('failed to read stage data:\n' + result.stderr)
    return json.loads(result.stdout)


def key_for(text):
    return hashlib.sha1(text.encode('utf-8')).hexdigest()[:12]


async def render(text, path):
    speech = edge_tts.Communicate(text, VOICE, rate=RATE)
    await speech.save(path)


async def main():
    lines = collect_lines()
    os.makedirs(OUT_DIR, exist_ok=True)

    index = {}
    made = skipped = 0

    for text in lines:
        name = key_for(text) + '.mp3'
        path = os.path.join(OUT_DIR, name)
        index[text] = OUT_DIR.replace(os.sep, '/') + '/' + name

        if os.path.exists(path) and os.path.getsize(path) > 0:
            skipped += 1
            continue
        await render(text, path)
        made += 1
        print('  rendered  %s  %s' % (name, text[:34]))

    # A .js file rather than .json so it works over file:// too, where fetch()
    # of a local JSON file is blocked as a cross-origin request.
    #
    # Assigned to `self`, not `window`: in a page self === window, and in the
    # service worker self is the worker global. That lets sw.js importScripts()
    # this same file to build its pre-cache list, so the audio paths have one
    # source of truth instead of being copied into two places.
    body = (
        '/* Generated by generate-audio.py - do not edit.\n'
        '   Maps each spoken line to its pre-rendered %s clip. */\n'
        'self.LanternAlleyAudio = %s;\n'
    ) % (VOICE, json.dumps(index, ensure_ascii=False, indent=2, sort_keys=True))
    open(INDEX_JS, 'w', encoding='utf-8', newline='').write(body)

    # Drop clips for lines that no longer exist, so edited sentences do not
    # leave their old audio behind to be shipped and cached forever.
    wanted = {key_for(text) + '.mp3' for text in lines}
    pruned = 0
    for name in os.listdir(OUT_DIR):
        if name.endswith('.mp3') and name not in wanted:
            os.remove(os.path.join(OUT_DIR, name))
            pruned += 1
            print('  pruned    %s' % name)

    total = sum(os.path.getsize(os.path.join(OUT_DIR, f)) for f in os.listdir(OUT_DIR))
    print('\n%d lines: %d rendered, %d unchanged, %d pruned' % (len(lines), made, skipped, pruned))
    print('%s  %.0f KB total' % (OUT_DIR, total / 1024))
    print('wrote %s' % INDEX_JS)


asyncio.run(main())
